Friend Module Constants
    Friend Const AvatarCharacterType As String = "Avatar"
    Friend Const CanShaveTag As String = "CanShave"
    Friend Const ColumnStatistic As String = "Column"
    Friend Const EastDirection As String = "East"
    Friend Const InteractionCharacterIdTrait As String = "InteractionCharacterId"
    Friend Const NorthDirection As String = "North"
    Friend Const OverworldTag As String = "Overworld"
    Friend Const RowStatistic As String = "Row"
    Friend Const ShaveInteraction As String = "Shave"
    Friend Const SouthDirection As String = "South"
    Friend Const WestDirection As String = "West"
    Friend Const YakHairItemType As String = "YakHair"
    Friend Const YakHairName As String = "Yak Hair"
End Module
